### ISSUE TITLE
[Bug] Baron calculation error

### ISSUE THREAD

**Issue by jie65535** [DivvyCr/Balatro-Preview#1]
The preview score when selecting K includes the Baron effect.

**Comment by DivvyCr** [comment]
> The preview score when selecting K includes the Baron effect.

What do you mean by this? From my testing, Baron is always calculated correctly.

**Comment by jie65535** [comment]
Maybe I guessed wrong, because in one game I played K and the actual score was much lower than expected.

 If I encounter it again, I will provide feedback.
