### ISSUE TITLE
New Crash Issue

### ISSUE THREAD

**Issue by Yacabolet** [DivvyCr/Balatro-Preview#12]
Crash whenever I select a card with the following screen:
![CrashReport](https://github.com/DivvyCr/Balatro-Preview/assets/24775669/83fd35fd-7c46-4560-ab15-4c6f11d5af42)

**Comment by DivvyCr** [comment]
Hmmm, this is odd. Are you using any modded jokers/cards/etc.? My mod is not compatible with those just yet.

Can you remember what jokers you had when this happened?

**Comment by Yacabolet** [comment]
It would appear to be an issue with Steam Modded version 0.9.6 specifically, and it was giving other crashes too. Trying on 0.9.7 seems to have solved the problem.
