### ISSUE TITLE
Crash by `Money Tree` and `The Hook` 

### ISSUE THREAD

**Issue by jie65535** [DivvyCr/Balatro-Preview#13]
![E7X@66~C7`8G(78$C9U0_QI_tmb](https://github.com/DivvyCr/Balatro-Preview/assets/29452349/1c355f68-97f7-47dd-a0bc-eb1fafeca1e3)

![RM06X8YL1G(SN)4J(KPHKG9](https://github.com/DivvyCr/Balatro-Preview/assets/29452349/13238301-4c71-4731-8be1-4b3caf683ec4)

**Comment by DivvyCr** [comment]
This looks like it's on v2.0.0, which is the most unstable pre-release. Try upgrading to v2.0.5 which is the latest at the moment, it's at the same [link](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v2.0), just a different download.

**Comment by DivvyCr** [comment]
Fixed in [v2.1](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v2.1)
