### ISSUE TITLE
Money estimates are x2 the real output

### ISSUE THREAD

**Issue by begna112** [DivvyCr/Balatro-Preview#14]
I noticed it especially on Lucky cards which show +40 for a single card, but also applies to gold seal at least. 
![](https://i.ddy.moe/2024/04/Balatro_240405-073801.jpg)

**Comment by DivvyCr** [comment]
I believe this was fixed in v1.9.1. Do you remember what version you're on?

**Comment by begna112** [comment]
Well I just installed it today, so it looks like 1.9.2, the one that was in the releases. But I don't see any way to identify it for sure.  
CRC hashes:
preview - 697D0905
simulate - BBEF6D88

could it maybe be due to latest steamodded? 0.9.7 was released 9 hours ago.

**Comment by DivvyCr** [comment]
Ah, if you've installed latest today, then it's definitely a bug. I've not tested with latest Steamodded, but that shouldn't cause any problems. This is likely a bug.

As I've mentioned on your [other issue](https://github.com/DivvyCr/Balatro-Preview/issues/15), I'm working on a rewrite that fixes this, too. I'll only attend to this bug if that rewrite is delayed.

**Comment by DivvyCr** [comment]
Fixed in [v2.1](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v2.1). However, note that v2.1 does not support mods, it just ignores all modded jokers.
