### ISSUE TITLE
v2.1 Immediately crashes

### ISSUE THREAD

**Issue by erijohnt** [DivvyCr/Balatro-Preview#16]
Installed v2.1 with Steamodded v0.9.8 and it crashes immediately when attempting to start a new hand (i.e. after selecting the first blind). No other mods were installed at the time of the crash.

<img width="1552" alt="Screenshot 2024-04-06 at 9 02 05 PM" src="https://github.com/DivvyCr/Balatro-Preview/assets/12579154/9c288533-b04e-4154-bfb3-cb6ef545bb4e">

I'm not familiar with Lua or this modding setup, but it seems like the script is trying to invoke `DV.deep_copy` [here](https://github.com/DivvyCr/Balatro-Preview/blob/a034701e280766b22ef6c58ffb6f7301d8951db2/Mods/DVPreview.lua#L55) even though the `DV` table doesn't have a field with that name.

**Comment by erijohnt** [comment]
Looks like it was a helper function that got deleted in the refactor
https://github.com/DivvyCr/Balatro-Preview/commit/a034701e280766b22ef6c58ffb6f7301d8951db2#diff-3b207e3330cffa6708754b55038015e9cdc5ab9dbdead96a3798851c8f5159cbL536-L552

**Comment by erijohnt** [comment]
I re-added the helper function and that seems to have fixed things? I'm not sure if the score calculations are accurate but it at least get a score preview now. #17

**Comment by DivvyCr** [comment]
Appreciate the Pull Request, but it was a different problem. I forgot to update the version of DVPreview in the release, so sorry! Fixed in [v2.2](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v2.2)
