### ISSUE TITLE
Game crashes when simulating Odd Todd or Even Steven

### ISSUE THREAD

**Issue by erijohnt** [DivvyCr/Balatro-Preview#18]
The card object wasn't being properly passed to the parity checking, causing the game to crash when simulating scoring for Even Steven and Odd Todd.

<img width="1552" alt="Screenshot 2024-04-06 at 9 59 35 PM" src="https://github.com/DivvyCr/Balatro-Preview/assets/12579154/f10726f4-f2a4-46fa-806b-191e6abc5865">

**Comment by DivvyCr** [comment]
Fixed in [v2.2](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v2.2)
