### ISSUE TITLE
Simulation can cause joker triggers without playing hand

### ISSUE THREAD

**Issue by begna112** [DivvyCr/Balatro-Preview#20]
Knowing that you have a rewrite on the way, and it may eventually support modded jokers, I wanted to pass along this issue. 

DVPreview apparently can cause some jokers to retrigger as soon as any card or joker is moved, selected, etc without a hand being played.

More info:
https://github.com/batabata3/balatro-pampa-joker-pack/issues/3

**Comment by begna112** [comment]
I missed that you had released v2. maybe this is already fixed?

**Comment by DivvyCr** [comment]
Versions <v2.0 are incompatible with other mods.

Later versions currently ignore all modded jokers, until they implement simulation functions. The timeline for those is on the scale of weeks.
