### ISSUE TITLE
Crimson Heart debuff not triggering

### ISSUE THREAD

**Issue by n4ru** [DivvyCr/Balatro-Preview#21]
Despite there being a `joker_obj.debuff` check in `DV.SIM.simulate_joker`, the debuffed Joker is still used in the simulation.

**Comment by DivvyCr** [comment]
Huh, weird, thanks for reporting!

**Comment by DivvyCr** [comment]
Fixed in 9b34ca9178efd714bb3a3889d86ecb0cb6662a21
Download [here](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v2.2.1)
