### ISSUE TITLE
"attempt to index a nil value" -- game crash caused by simulation.

### ISSUE THREAD

**Issue by n4ru** [DivvyCr/Balatro-Preview#22]
![image](https://github.com/DivvyCr/Balatro-Preview/assets/481177/552b3a00-f959-449d-aafd-4606e18e31b9)

No other mods installed. It crashes when selecting the 5th card which is also a Bonus card. Able to trigger consistently upon relaunching.

**Comment by DivvyCr** [comment]
Do you remember what your hand size was? and, I think this must have taken place during The Hook blind, is that right?

**Comment by DivvyCr** [comment]
Fixed in 62d2941d4ee41024c846703fc01f45dcb3aa70e5 I think
It will be included in v2.3, once Balatro updates to v1.0.1; if you're already on the experimental version, feel free to download the pre-release [here](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v2.3).
