### ISSUE TITLE
[Bug] Blueprint on Vagabond creates Tarots during simulation

### ISSUE THREAD

**Issue by jie65535** [DivvyCr/Balatro-Preview#3]

**Comment by jie65535** [comment]
After retesting, it was caused by the blueprint.

**Comment by jie65535** [comment]
When the blueprint is in front of the Vagabond, it triggers every calculation. I speculate that similar clowns may have the same problem.

**Comment by DivvyCr** [comment]
Fixed in v1.4, download [here](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v1.4)
