### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by rickbonnell** [DivvyCr/Balatro-Preview#31]
Great Mod. But I still have to do some math. Any way there could be a total added (previous chips + current hand preview?)

Thanks!

**Comment by DivvyCr** [comment]
What's the reason for knowing the exact total after round? I find that the two comparisons I'm looking for when calculating score are: (1) order of magnitude of the score (is it a significant portion of the score?), and (2) whether it will clear the blind. Case (2) is already implemented, and Case (1) is easy enough to approximate.

Just looking to get some clarity for the necessity of adding a new feature.

**Comment by rickbonnell** [comment]
I don't like having to do the math to see whether the current hand will win
the round or not. Maybe just turn the preview count green if the current
hand will "win"?

Again. Awesome mod. Should have been in main game!

**Comment by rickbonnell** [comment]
Sorry.my bad. The feature I wanted is there, I just didn't know how it
worked apparently. I'm a dummy. Sorry to have bothered you!

**Comment by rickbonnell** [comment]
Your mod is quite complex. Must have taken a long time to get right. I think I missed the "hand will win" feature because the color blended in with the UI, so I hope it's ok, I modded my copy to use red for "will not win" and dark green for "will win". And again, great work, I wish I knew more LUA :)

**Comment by rickbonnell** [comment]
Marking closed
