### ISSUE TITLE
It seems that after modded, you won't be able to unlock steam achievements anymore?

### ISSUE THREAD

**Issue by dive0511** [DivvyCr/Balatro-Preview#32]
I did not unlock the corresponding achievement after meeting the conditions. And changing to my original .exe , I was able to unlock that achievement. Is there a problem or am I done sth wrong? Anyway thank you for making such a good mod!

**Comment by DivvyCr** [comment]
This is a setting of Steamodded, not this mod. You can undo the setting by adding this file to your Mods folder: https://github.com/Steamopollys/Steamodded/blob/main/example_mods/Mods/AchievementsEnabler.lua

Unfortunately it will not retroactively unlock any achievements that you've earned with Steamodded.
