### ISSUE TITLE
The Arm off by 1 error

### ISSUE THREAD

**Issue by Ayre223** [DivvyCr/Balatro-Preview#33]
In the simulation for The Arm it incorrectly adds an extra `l_chips` and `l_mult` (it should use `played_hand_data.level - 1` like this)
```lua
         played_hand_data.mult = math.max(1, played_hand_data.s_mult + (played_hand_data.level - 1) * played_hand_data.l_mult)
         played_hand_data.chips = math.max(0, played_hand_data.s_chips + (played_hand_data.level - 1) * played_hand_data.l_chips)

**Comment by DivvyCr** [comment]
Fixed in https://github.com/DivvyCr/Balatro-Preview/commit/2fed466b7b54b2ec5348b195c5f28025d7a2fc92
Download [here](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v2.5)
