### ISSUE TITLE
Game crash when card is selected

### ISSUE THREAD

**Issue by Servi18** [DivvyCr/Balatro-Preview#37]
I had boss blind The Club: all club cards are debuffed and when a card is selected game crash
![Screenshot_20241204_082215](https://github.com/user-attachments/assets/521b3766-e8d5-47aa-9a4a-9ce36b6d8d82)
I'm using release 3.0, i tried with 2.5 and didn't crash

**Comment by DivvyCr** [comment]
Shit, my bad. Should be fixed in [v3.1](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v3.1).
Sorry for late update.
