### ISSUE TITLE
will crash in this case

### ISSUE THREAD

**Issue by LemonLiquor** [DivvyCr/Balatro-Preview#38]
![image](https://github.com/user-attachments/assets/3466ec13-6724-410b-8c8b-5c46bbf9f240)
## when I chose the card hearts 2, the game will crash

here is the log:

Oops! The game crashed:
card.lua:5000: attempt to call field 'add_type_mult' (a nil value)

Additional Context:
Balatro Version: 1.0.1m-FULL
Modded Version: 1.0.0~ALPHA-1203b-STEAMODDED
Love2D Version: 11.5.0
Lovely Version: 0.6.0
Steamodded Mods:
Lovely Mods:
    1: DVPreview
    2: DVSimulate

Stack Traceback
===============
(3) Lua local 'joker_simulation_function' at file 'card.lua:5000'
Local variables:
 joker_obj = table: 0x3a32e048  {id:crazy, debuff:false, rarity:1, ability:table: 0x3a32e138}
 context = table: 0x3a700078  {before:true, scoring_name:High Card, scoring_hand:table: 0x39f54710, full_hand:table: 0x39f546e8 (more...)}
 (*temporary) = nil
 (*temporary) = table: 0x3a32e048  {id:crazy, debuff:false, rarity:1, ability:table: 0x3a32e138}
 (*temporary) = table: 0x3a700078  {before:true, scoring_name:High Card, scoring_hand:table: 0x39f54710, full_hand:table: 0x39f546e8 (more...)}
 (*temporary) = string: "attempt to call field 'add_type_mult' (a nil value)"
(4) Lua field 'simulate_joker' at file 'functions/common_events.lua:3389'
Local variables:
 joker_obj = table: 0x3a32e048  {id:crazy, debuff:false, rarity:1, ability:table: 0x3a32e138}
 context = table: 0x3a700078  {before:true, scoring_name:High Card, scoring_hand:table: 0x39f54710, full_hand:table: 0x39f546e8 (more...)}
 joker_simulation_function = Lua function '?' (defined at line 4999 of chunk card.lua)
(5) Lua field 'simulate_joker_before_effects' at file 'functions/common_events.lua:3197'
Local variables:
 (for generator) = C function: builtin#6
 (for state) = table: 0x3a7e7ee8  {1:table: 0x3a7e7f10, 2:table: 0x3a7e8050, 3:table: 0x3a7e8190, 4:table: 0x3a7788d0 (more...)}
 (for control) = number: 5
 _ = number: 5
 joker = table: 0x3a32e048  {id:crazy, debuff:false, rarity:1, ability:table: 0x3a32e138}
(6) Lua field 'simulate' at file 'functions/common_events.lua:2985'
Local variables:
 null_ret = table: 0x3a2e4480  {dollars:table: 0x3a2e44d0, score:table: 0x3a2e44a8}
(7) Lua field 'func' at file 'main.lua:1340'
Local variables:
 (*temporary) = table: 0x3a0716e8  {joker_order:table: 0x3a347f48, is_enough_to_win:function: 0x3a065870, get_score_node:function: 0x3a065830 (more...)}
(8) Lua method 'handle' at file 'engine/event.lua:99'
Local variables:
 self = table: 0x3a144f70  {start_timer:true, timer:TOTAL, blockable:true, trigger:immediate, func:function: 0x3a35abe0 (more...)}
 _results = table: 0x3a648e68  {blocking:true, pause_skip:false, time_done:false, completed:false}
(9) Lua method 'update' at file 'engine/event.lua:182'
Local variables:
 self = table: 0x3a685910  {queue_last_processed:18.25, queues:table: 0x3a685938, queue_dt:0.016666666666667 (more...)}
 dt = number: 0.00206842
 forced = nil
 (for generator) = C function: next
 (for state) = table: 0x3a685938  {unlock:table: 0x3a685960, other:table: 0x3a685dd8, tutorial:table: 0x3a6859b0 (more...)}
 (for control) = number: nan
 k = string: "base"
 v = table: 0x3a685988  {1:table: 0x3a63a410, 2:table: 0x3aa25bc0, 3:table: 0x3a68ff18, 4:table: 0x3a144f70 (more...)}
 blocked = boolean: false
 i = number: 4
 results = table: 0x3a648e68  {blocking:true, pause_skip:false, time_done:false, completed:false}
(10) Lua upvalue 'gameUpdateRef' at file 'game.lua:2502'
Local variables:
 self = table: 0x39f3ea38  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3aa47080 (more...)}
 dt = number: 0.00206842
 http_resp = nil
(11) Lua method 'update' at Steamodded file 'core/ui.lua:81' 
Local variables:
 self = table: 0x39f3ea38  {F_GUIDE:false, F_CRASH_REPORTS:false, F_QUIT_BUTTON:true, HUD_tags:table: 0x3aa47080 (more...)}
 dt = number: 0.00206842
(12) Lua field 'update' at file 'main.lua:965'
Local variables:
 dt = number: 0.00206842
(13) Lua function '?' at file 'main.lua:909' (best guess)
(14) global C function 'xpcall'
(15) Love2D function at file 'boot.lua:377' (best guess)
Local variables:
 func = Lua function '?' (defined at line 880 of chunk main.lua)
 inerror = boolean: true
 deferErrhand = Lua function '(Love2D Function)' (defined at line 348 of chunk [love "boot.lua"])
 earlyinit = Lua function '(Love2D Function)' (defined at line 355 of chunk [love "boot.lua"])

**Comment by hazawamaja** [comment]
I have encountered the same issue. I reverted to 2.5 release and continued from the crashing spot, and the mod is very stable. So it seems like it must be something within the newest update that broke the mod.

Environment:
macOS Sequoia 15.1, only other mods are more speed options and better mouse actions.

**Comment by DivvyCr** [comment]
Shit, my bad. Should be fixed in [v3.1](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v3.1).
Sorry for late update.
