### ISSUE TITLE
[Bug] card.lua:5367: attempt to call field x_mult_if_global (a nil value)

### ISSUE THREAD

**Issue by drgrib** [DivvyCr/Balatro-Preview#39]
I'm on the latest version of Balatro on Steam Deck. I see no option in Settings to turn on Crash Reports. Crash happens when any card is selected for any ordering of the jokers I have tried. I have specifically tried to move Blueprint to all possible positions and it still crashes and I have tried selecting either the 4 or the far left King.

![hand](https://github.com/user-attachments/assets/7de74eab-23e0-4380-97d5-146f8fd6f4f1)
![error](https://github.com/user-attachments/assets/36e7045c-ca00-4749-82f6-2bf80c046eb1)

**Comment by DivvyCr** [comment]
Shit, my bad. Should be fixed in [v3.1](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v3.1).
Sorry for late update.

**Comment by drgrib** [comment]
Awesome. Looks like it is working now. Thanks. Btw, it looks like this added a new folder (something `Settings`) that isn't mentioned in the readme.

**Comment by DivvyCr** [comment]
Yeah, it's another small update. Just putting all my mod settings in one place (in a separate game options tab).

What would you expect to see in the README? Might want to update it to add any clarifications.

**Comment by drgrib** [comment]
Made #40 with what I was talking about, assuming I'm remembering the directory name correctly.
