### ISSUE TITLE
[Bug] To Do List will be triggered

### ISSUE THREAD

**Issue by jie65535** [DivvyCr/Balatro-Preview#4]
![QG9R71 $3$S$THFD064A2J4](https://github.com/DivvyCr/Balatro-Preview/assets/29452349/6387ec6a-c82e-47da-af55-87bc14ed8443)
![0RZQ(%%J5K9A(ZR5TA(UJQ7_tmb](https://github.com/DivvyCr/Balatro-Preview/assets/29452349/2f3ad531-7258-4c88-929f-c3b60f8fdf08)

**Comment by DivvyCr** [comment]
Fixed in v1.5, download [here](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v1.5)
