### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by kymynhuy** [DivvyCr/Balatro-Preview#42]
Settings are not saved, it returns to default after restarting the game. I only run this mod.

**Comment by MindLines** [comment]
Same

**Comment by MindLines** [comment]
%appdata%\Balatro\Mods\DVPreview
open file init.lua
change "G.SETTINGS.DV.show_min_max" to true

**Comment by kymynhuy** [comment]
> %appdata%\Balatro\Mods\DVPreview open file init.lua change "G.SETTINGS.DV.show_min_max" to true

Work like a charm, thanks

**Comment by DivvyCr** [comment]
Fixed in [v3.2](https://github.com/DivvyCr/Balatro-Preview/releases/tag/v3.2)
Sorry for taking a while, it's holiday season.
